version: '3.9'

services:
  moonsuit:
    image: gglamer/moonsuit:latest
    container_name: moonsuit_web
    restart: always
    depends_on:
      - redis
      - nginx
    environment:
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_PASSWORD=root
      - DJANGO_SUPERUSER_EMAIL=root@root.ru
      - PASSWORD=1234
      - EMAIL=azama@ya.ru
    command: ["bash", "./startup.sh"]
    networks:
      - moonsuit_network
    volumes:
      - ./moonsuit.db:/moonsuit/moonsuit.db

  nginx:
    container_name: moonsuit_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - moonsuit_network
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  redis:
    container_name: moonsuit_redis
    image: redis:latest
    networks:
      - moonsuit_network


networks:
  moonsuit_network:
    driver: bridge

