# Generated by Django 4.0.6 on 2022-09-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('controlling', models.JSONField(default={'hello': 'World'})),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('z', models.IntegerField(blank=True, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('vibration', models.IntegerField(blank=True, null=True)),
                ('bodytemp', models.FloatField(blank=True, null=True)),
                ('tempin', models.FloatField(blank=True, null=True)),
                ('humin', models.IntegerField(blank=True, null=True)),
                ('pressurein', models.IntegerField(blank=True, null=True)),
                ('tempout', models.FloatField(blank=True, null=True)),
                ('pressureout', models.IntegerField(blank=True, null=True)),
                ('tempcontrol', models.IntegerField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o', models.FloatField(blank=True, null=True)),
                ('pressureinairsys', models.FloatField(blank=True, null=True)),
                ('speedflowair', models.FloatField(blank=True, null=True)),
                ('tempbefore', models.FloatField(blank=True, null=True)),
                ('tempafter', models.FloatField(blank=True, null=True)),
                ('speedflowcooling', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
