# Generated by Django 4.0.6 on 2022-07-14 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('datas', models.JSONField(blank=True)),
                ('controlling', models.JSONField(blank=True)),
                ('key', models.UUIDField(default=uuid.UUID('acd592ff-0b87-4e5d-9c12-a0ade40649a4'), primary_key=True, serialize=False)),
            ],
        ),
    ]
