# Generated by Django 4.0.6 on 2022-07-28 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.UUIDField(default=uuid.UUID('63677916-bdcd-46f4-a43a-4b0d4f898c94'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='tag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
