# Generated by Django 4.0.6 on 2022-07-15 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.UUIDField(default=uuid.UUID('57edb527-59a6-4fc1-838e-da44a025ce56'), primary_key=True, serialize=False),
        ),
    ]
