# Generated by Django 4.0.6 on 2022-07-15 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_device_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9bceef8b-062b-42d6-a16b-6610a32c42de'), primary_key=True, serialize=False),
        ),
    ]
