# Generated by Django 4.0.6 on 2022-07-28 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_device_key_alter_device_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
