# Generated by Django 4.0.6 on 2022-07-15 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_device_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.UUIDField(default=uuid.UUID('a80a8e75-a0b3-4079-a941-5dccb9bf5d92'), primary_key=True, serialize=False),
        ),
    ]
